/*
 * Opcode names and the 0x00-0x75 values are derived from cutile-ir:
 *   SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
 *   SPDX-License-Identifier: Apache-2.0
 */
//! Opcode vocabulary.
//!
//! Forked from `cutile_ir`. Verified against upstream's table
//! (`cuda-tile/include/cuda_tile/Dialect/CudaTile/IR/BytecodeOpcodes.td`)

/// A tile-level operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[repr(u16)]
pub enum Opcode {
    AbsF = 0x00,
    AbsI = 0x01,
    AddF = 0x02,
    AddI = 0x03,
    AndI = 0x04,
    Assert = 0x05,
    Assume = 0x06,
    AtomicCAS = 0x07,
    AtomicRMW = 0x08,
    Bitcast = 0x09,
    Break = 0x0A,
    Broadcast = 0x0B,
    Cat = 0x0C,
    Ceil = 0x0D,
    CmpF = 0x0E,
    CmpI = 0x0F,
    Constant = 0x10,
    Continue = 0x11,
    Cos = 0x12,
    CosH = 0x13,
    DivF = 0x14,
    DivI = 0x15,
    Entry = 0x16,
    Exp = 0x17,
    Exp2 = 0x18,
    ExtI = 0x25,
    Extract = 0x26,
    Floor = 0x27,
    Fma = 0x28,
    For = 0x29,
    FToF = 0x2A,
    FToI = 0x2B,
    GetGlobal = 0x2C,
    GetIndexSpaceShape = 0x2D,
    GetNumTileBlocks = 0x2E,
    GetTensorShape = 0x2F,
    GetTileBlockId = 0x30,
    Global = 0x31,
    If = 0x32,
    IntToPtr = 0x33,
    Iota = 0x3A,
    IToF = 0x3B,
    JoinTokens = 0x3C,
    LoadPtrTko = 0x3D,
    LoadViewTko = 0x3E,
    Log = 0x3F,
    Log2 = 0x40,
    Loop = 0x41,
    MakePartitionView = 0x42,
    MakeTensorView = 0x43,
    MakeToken = 0x44,
    MaxF = 0x45,
    MaxI = 0x46,
    MinF = 0x47,
    MinI = 0x48,
    MmaF = 0x49,
    MmaI = 0x4A,
    Module = 0x4B,
    MulF = 0x4C,
    MulhiI = 0x4D,
    MulI = 0x4E,
    NegF = 0x4F,
    NegI = 0x50,
    Offset = 0x51,
    OrI = 0x52,
    Permute = 0x53,
    Pow = 0x54,
    Print = 0x55,
    PtrToInt = 0x56,
    PtrToPtr = 0x57,
    Reduce = 0x58,
    RemF = 0x59,
    RemI = 0x5A,
    Reshape = 0x5B,
    Return = 0x5C,
    Rsqrt = 0x5D,
    Scan = 0x5E,
    Select = 0x5F,
    ShLI = 0x60,
    ShRI = 0x61,
    Sin = 0x62,
    SinH = 0x63,
    Sqrt = 0x64,
    StorePtrTko = 0x65,
    StoreViewTko = 0x66,
    SubF = 0x67,
    SubI = 0x68,
    Tan = 0x69,
    TanH = 0x6A,
    TruncI = 0x6B,
    XOrI = 0x6C,
    Yield = 0x6D,
    Atan2 = 0x6E,
    Pack = 0x6F,
    Unpack = 0x70,
    Alloca = 0x71,
    MmaFScaled = 0x72,
    MakeGatherScatterView = 0x73,
    MakeStridedView = 0x74,
    AtomicRedViewTko = 0x75,
    // On potentially extending with custom op codes:
    // Theoretically it should be safe to reserve 0x1000+ for backend-specific extension opcodes.
    // We can't guarantee that to be true in perpetuity, but it seems unlikely that cutile will
    // extend its vocabulary beyond 0xFF.
    //
    // Adding a new opcode requires four updates:
    //   1. here + the `ALL` list below
    //   2. `dialect::ops` or `dialect::attrs`
    //   3. frontend intrinsic dispatch
    //   4. backend lowering
}

impl Opcode {
    /// The raw value, for bytecode emission.
    pub fn as_u16(self) -> u16 {
        self as u16
    }

    /// All opcodes. Let's consumers prove they support all ops, not just what's covered by test kernels etc.
    // TODO: Arguably we should use a macro/crate to ensure this is always kept up to date with the enum itself.
    pub const ALL: [Opcode; 100] = [
        Opcode::AbsF,
        Opcode::AbsI,
        Opcode::AddF,
        Opcode::AddI,
        Opcode::AndI,
        Opcode::Assert,
        Opcode::Assume,
        Opcode::AtomicCAS,
        Opcode::AtomicRMW,
        Opcode::Bitcast,
        Opcode::Break,
        Opcode::Broadcast,
        Opcode::Cat,
        Opcode::Ceil,
        Opcode::CmpF,
        Opcode::CmpI,
        Opcode::Constant,
        Opcode::Continue,
        Opcode::Cos,
        Opcode::CosH,
        Opcode::DivF,
        Opcode::DivI,
        Opcode::Entry,
        Opcode::Exp,
        Opcode::Exp2,
        Opcode::ExtI,
        Opcode::Extract,
        Opcode::Floor,
        Opcode::Fma,
        Opcode::For,
        Opcode::FToF,
        Opcode::FToI,
        Opcode::GetGlobal,
        Opcode::GetIndexSpaceShape,
        Opcode::GetNumTileBlocks,
        Opcode::GetTensorShape,
        Opcode::GetTileBlockId,
        Opcode::Global,
        Opcode::If,
        Opcode::IntToPtr,
        Opcode::Iota,
        Opcode::IToF,
        Opcode::JoinTokens,
        Opcode::LoadPtrTko,
        Opcode::LoadViewTko,
        Opcode::Log,
        Opcode::Log2,
        Opcode::Loop,
        Opcode::MakePartitionView,
        Opcode::MakeTensorView,
        Opcode::MakeToken,
        Opcode::MaxF,
        Opcode::MaxI,
        Opcode::MinF,
        Opcode::MinI,
        Opcode::MmaF,
        Opcode::MmaI,
        Opcode::Module,
        Opcode::MulF,
        Opcode::MulhiI,
        Opcode::MulI,
        Opcode::NegF,
        Opcode::NegI,
        Opcode::Offset,
        Opcode::OrI,
        Opcode::Permute,
        Opcode::Pow,
        Opcode::Print,
        Opcode::PtrToInt,
        Opcode::PtrToPtr,
        Opcode::Reduce,
        Opcode::RemF,
        Opcode::RemI,
        Opcode::Reshape,
        Opcode::Return,
        Opcode::Rsqrt,
        Opcode::Scan,
        Opcode::Select,
        Opcode::ShLI,
        Opcode::ShRI,
        Opcode::Sin,
        Opcode::SinH,
        Opcode::Sqrt,
        Opcode::StorePtrTko,
        Opcode::StoreViewTko,
        Opcode::SubF,
        Opcode::SubI,
        Opcode::Tan,
        Opcode::TanH,
        Opcode::TruncI,
        Opcode::XOrI,
        Opcode::Yield,
        Opcode::Atan2,
        Opcode::Pack,
        Opcode::Unpack,
        Opcode::Alloca,
        Opcode::MmaFScaled,
        Opcode::MakeGatherScatterView,
        Opcode::MakeStridedView,
        Opcode::AtomicRedViewTko,
    ];

    // TOOD: Uncomment if we add custom op codes
    //pub fn is_backend_extension(self) -> bool {
    //    self.as_u16() >= 0x1000
    //}
}
