#[cfg(feature = "mkl")]
extern crate intel_mkl_src;

#[cfg(feature = "accelerate")]
extern crate accelerate_src;

use anyhow::Result;
use clap::{Parser, ValueEnum};
use std::io::Write;
use std::path::PathBuf;
use tokenizers::Tokenizer;

use candle::quantized::gguf_file;
use candle::quantized::tokenizer::TokenizerFromGguf;
use candle::Tensor;
use candle_transformers::generation::{LogitsProcessor, Sampling};

use candle_examples::token_output_stream::TokenOutputStream;
use candle_transformers::models::quantized_lfm2::ModelWeights;

const DEFAULT_PROMPT: &str = "Explain how Rotary Position Embeddings work in transformers.";

#[derive(Clone, Debug, Copy, PartialEq, Eq, ValueEnum)]
enum Which {
    #[value(name = "lfm2-350m")]
    Lfm2_350M,
    #[value(name = "lfm2-2.6b")]
    Lfm2_2_6B,
    #[value(name = "lfm2.5-230m")]
    Lfm2_5_230M,
    #[value(name = "lfm2.5-350m")]
    Lfm2_5_350M,
    #[value(name = "lfm2.5-1.2b-base")]
    Lfm2_5_1_2BBase,
    #[value(name = "lfm2.5-1.2b-instruct")]
    Lfm2_5_1_2BInstruct,
    #[value(name = "lfm2.5-1.2b-thinking")]
    Lfm2_5_1_2BThinking,
    #[value(name = "lfm2.5-1.2b-jp")]
    Lfm2_5_1_2BJp,
    #[value(name = "lfm2.5-1.2b-jp-202606")]
    Lfm2_5_1_2BJp202606,
    #[value(name = "lfm2.5-2.6b")]
    Lfm2_5_2_6B,
    #[value(name = "lfm2.5-8b-a1b")]
    Lfm2_5_8BA1B,
}

impl Which {
    /// The model name, `LiquidAI/<name>-GGUF` holds `<name>-<quant>.gguf`.
    fn name(&self) -> &'static str {
        match self {
            Which::Lfm2_350M => "LFM2-350M",
            Which::Lfm2_2_6B => "LFM2-2.6B",
            Which::Lfm2_5_230M => "LFM2.5-230M",
            Which::Lfm2_5_350M => "LFM2.5-350M",
            Which::Lfm2_5_1_2BBase => "LFM2.5-1.2B-Base",
            Which::Lfm2_5_1_2BInstruct => "LFM2.5-1.2B-Instruct",
            Which::Lfm2_5_1_2BThinking => "LFM2.5-1.2B-Thinking",
            Which::Lfm2_5_1_2BJp => "LFM2.5-1.2B-JP",
            Which::Lfm2_5_1_2BJp202606 => "LFM2.5-1.2B-JP-202606",
            Which::Lfm2_5_2_6B => "LFM2.5-2.6B",
            Which::Lfm2_5_8BA1B => "LFM2.5-8B-A1B",
        }
    }
}

#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Args {
    /// GGUF file to load, typically a .gguf file generated by llama.cpp.
    #[arg(long)]
    model: Option<String>,

    /// The model to download from Hugging Face when --model is not set.
    #[arg(long, default_value = "lfm2.5-1.2b-instruct")]
    which: Which,

    /// The quantization to download, e.g. Q4_0, Q4_K_M, Q5_K_M, Q6_K, Q8_0 or F16.
    #[arg(long, default_value = "Q4_K_M")]
    quant: String,

    /// Repo revision to download from when using --which.
    #[arg(long, default_value = "main")]
    revision: String,

    /// Path to tokenizer.json. Defaults to the tokenizer stored in the GGUF file.
    #[arg(long)]
    tokenizer: Option<String>,

    /// The initial prompt to feed to the model.
    #[arg(long)]
    prompt: Option<String>,

    /// The number of tokens to sample (including the first token after the prompt).
    #[arg(short = 'n', long, default_value_t = 512)]
    sample_len: usize,

    /// The temperature used to generate samples, use 0 for greedy sampling.
    #[arg(long, default_value_t = 0.8)]
    temperature: f64,

    /// Nucleus sampling probability cutoff.
    #[arg(long)]
    top_p: Option<f64>,

    /// Only sample among the top K samples.
    #[arg(long)]
    top_k: Option<usize>,

    /// The seed to use when generating random samples.
    #[arg(long, default_value_t = 299792458)]
    seed: u64,

    /// Enable tracing (generates a trace-timestamp.json file).
    #[arg(long)]
    tracing: bool,

    /// Process prompt elements separately.
    #[arg(long)]
    split_prompt: bool,

    /// Run on CPU rather than GPU even if a GPU is available.
    #[arg(long)]
    cpu: bool,

    /// Penalty to be applied for repeating tokens, 1. means no penalty.
    #[arg(long, default_value_t = 1.1)]
    repeat_penalty: f32,

    /// The context size to consider for the repeat penalty.
    #[arg(long, default_value_t = 64)]
    repeat_last_n: usize,
}

impl Args {
    fn model_path(&self) -> Result<PathBuf> {
        if let Some(model) = &self.model {
            return Ok(PathBuf::from(model));
        }
        let name = self.which.name();
        let repo = format!("LiquidAI/{name}-GGUF");
        let filename = format!("{name}-{}.gguf", self.quant.to_uppercase());
        let api = candle_examples::hub::Api::new()?;
        api.model(repo)
            .with_revision(self.revision.clone())
            .get(&filename)
            .map_err(Into::into)
    }

    fn tokenizer(&self, gguf: &gguf_file::Content) -> Result<Tokenizer> {
        match &self.tokenizer {
            Some(path) => Tokenizer::from_file(path).map_err(anyhow::Error::msg),
            // The GGUF file carries its own tokenizer, LFM2.5 models do not all share one.
            None => Ok(Tokenizer::from_gguf(gguf)?),
        }
    }
}

fn format_size(size_in_bytes: usize) -> String {
    if size_in_bytes < 1_000 {
        format!("{size_in_bytes}B")
    } else if size_in_bytes < 1_000_000 {
        format!("{:.2}KB", size_in_bytes as f64 / 1e3)
    } else if size_in_bytes < 1_000_000_000 {
        format!("{:.2}MB", size_in_bytes as f64 / 1e6)
    } else {
        format!("{:.2}GB", size_in_bytes as f64 / 1e9)
    }
}

fn guess_eos_id(tokenizer: &Tokenizer) -> Option<u32> {
    let vocab = tokenizer.get_vocab(true);
    let candidates = [
        "</s>",
        "<|im_end|>",
        "<|eot_id|>",
        "<|end|>",
        "<|end_of_text|>",
        "<|endoftext|>",
    ];
    candidates
        .iter()
        .find_map(|token| vocab.get(*token).copied())
}

fn main() -> Result<()> {
    use tracing_chrome::ChromeLayerBuilder;
    use tracing_subscriber::prelude::*;

    let args = Args::parse();
    let _guard = if args.tracing {
        let (chrome_layer, guard) = ChromeLayerBuilder::new().build();
        tracing_subscriber::registry().with(chrome_layer).init();
        Some(guard)
    } else {
        None
    };

    println!(
        "avx: {}, neon: {}, simd128: {}, f16c: {}",
        candle::utils::with_avx(),
        candle::utils::with_neon(),
        candle::utils::with_simd128(),
        candle::utils::with_f16c()
    );
    println!(
        "temp: {:.2} repeat-penalty: {:.2} repeat-last-n: {}",
        args.temperature, args.repeat_penalty, args.repeat_last_n
    );

    let model_path = args.model_path()?;
    let mut file = std::fs::File::open(&model_path)?;
    let start = std::time::Instant::now();
    let device = candle_examples::device(args.cpu)?;

    let gguf = gguf_file::Content::read(&mut file).map_err(|e| e.with_path(model_path.clone()))?;
    let mut total_size_in_bytes = 0;
    for tensor in gguf.tensor_infos.values() {
        let elem_count = tensor.shape.elem_count();
        total_size_in_bytes +=
            elem_count * tensor.ggml_dtype.type_size() / tensor.ggml_dtype.block_size();
    }

    let md_u32 = |key: &str| gguf.metadata.get(key).and_then(|v| v.to_u32().ok());
    let arch = match gguf.metadata.get("general.architecture") {
        Some(v) => v.to_string()?.clone(),
        None => "lfm2".to_string(),
    };
    let context_length = md_u32(&format!("{arch}.context_length")).map(|v| v as usize);
    let bos_token = md_u32("tokenizer.ggml.bos_token_id");
    let eos_token = md_u32("tokenizer.ggml.eos_token_id");

    println!(
        "loaded {:?} tensors ({}) in {:.2}s",
        gguf.tensor_infos.len(),
        format_size(total_size_in_bytes),
        start.elapsed().as_secs_f32()
    );

    let tokenizer = args.tokenizer(&gguf)?;
    let mut model = ModelWeights::from_gguf(gguf, &mut file, &device)?;
    println!("model ready");

    let mut tos = TokenOutputStream::new(tokenizer);
    let mut tokens = tos
        .tokenizer()
        .encode(args.prompt.as_deref().unwrap_or(DEFAULT_PROMPT), true)
        .map_err(anyhow::Error::msg)?
        .get_ids()
        .to_vec();
    // Some LFM2.5 tokenizers do not add the BOS token themselves.
    if let Some(bos) = bos_token {
        if tokens.first() != Some(&bos) {
            tokens.insert(0, bos);
        }
    }

    if let Some(max_ctx) = context_length {
        if tokens.len() >= max_ctx {
            let trim = tokens.len() - max_ctx + 1;
            tokens.drain(0..trim);
            println!("prompt trimmed to last {max_ctx} tokens to fit context");
        }
    }

    let mut all_tokens = tokens.clone();
    let to_sample = args.sample_len.saturating_sub(1);

    let mut logits_processor = {
        let temperature = args.temperature;
        let sampling = if temperature <= 0. {
            Sampling::ArgMax
        } else {
            match (args.top_k, args.top_p) {
                (None, None) => Sampling::All { temperature },
                (Some(k), None) => Sampling::TopK { k, temperature },
                (None, Some(p)) => Sampling::TopP { p, temperature },
                (Some(k), Some(p)) => Sampling::TopKThenTopP { k, p, temperature },
            }
        };
        LogitsProcessor::from_sampling(args.seed, sampling)
    };

    println!("Starting the inference loop:");
    let prompt_str = args.prompt.as_deref().unwrap_or(DEFAULT_PROMPT);
    print!("{prompt_str}");
    std::io::stdout().flush()?;

    let start_prompt_processing = std::time::Instant::now();
    let mut next_token = if !args.split_prompt {
        let input = Tensor::new(tokens.as_slice(), &device)?.unsqueeze(0)?;
        let logits = model.forward(&input, 0)?;
        let logits = logits.squeeze(0)?;
        logits_processor.sample(&logits)?
    } else {
        let mut next_token = 0;
        for (pos, token) in tokens.iter().enumerate() {
            let input = Tensor::new(&[*token], &device)?.unsqueeze(0)?;
            let logits = model.forward(&input, pos)?;
            let logits = logits.squeeze(0)?;
            next_token = logits_processor.sample(&logits)?
        }
        next_token
    };

    let index_pos_start = tokens.len();
    let prompt_dt = start_prompt_processing.elapsed();

    all_tokens.push(next_token);
    if let Some(t) = tos.next_token(next_token)? {
        print!("{t}");
        std::io::stdout().flush()?;
    }

    let eos_token = eos_token.or_else(|| guess_eos_id(tos.tokenizer()));
    let mut sampled = 0;
    let start_post_prompt = std::time::Instant::now();
    for (index_pos, _) in (index_pos_start..).zip(0..to_sample) {
        if let Some(max_ctx) = context_length {
            if index_pos + 1 > max_ctx {
                println!("\n\ncontext window of {max_ctx} reached, stopping generation");
                break;
            }
        }

        let input = Tensor::new(&[next_token], &device)?.unsqueeze(0)?;
        let logits = model.forward(&input, index_pos)?;
        let logits = logits.squeeze(0)?;
        let logits = if args.repeat_penalty == 1. {
            logits
        } else {
            let start_at = all_tokens.len().saturating_sub(args.repeat_last_n);
            candle_transformers::utils::apply_repeat_penalty(
                &logits,
                args.repeat_penalty,
                &all_tokens[start_at..],
            )?
        };
        next_token = logits_processor.sample(&logits)?;
        all_tokens.push(next_token);
        if let Some(t) = tos.next_token(next_token)? {
            print!("{t}");
            std::io::stdout().flush()?;
        }
        sampled += 1;
        if let Some(eos) = eos_token {
            if next_token == eos {
                break;
            }
        }
    }

    if let Some(rest) = tos.decode_rest().map_err(candle::Error::msg)? {
        print!("{rest}");
    }
    std::io::stdout().flush()?;

    let dt = start_post_prompt.elapsed();
    println!(
        "\n\n{:4} prompt tokens processed: {:.2} token/s",
        tokens.len(),
        tokens.len() as f64 / prompt_dt.as_secs_f64(),
    );
    println!(
        "{sampled:4} tokens generated: {:.2} token/s",
        sampled as f64 / dt.as_secs_f64(),
    );
    Ok(())
}
