/* tslint:disable */
/* eslint-disable */
export const __wbg_model_free: (a: number, b: number) => void;
export const model_chat: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number, number];
export const model_clear_conversation: (a: number) => void;
export const model_end_turn: (a: number) => void;
export const model_generate_tokens: (a: number, b: number) => [number, number, number, number];
export const model_get_cached_token_count: (a: number) => number;
export const model_get_conversation_json: (a: number) => [number, number];
export const model_get_message_count: (a: number) => number;
export const model_is_eos: (a: number) => number;
export const model_load: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const model_next_token: (a: number) => [number, number, number, number];
export const model_reset: (a: number) => void;
export const model_start_conversation: (a: number, b: number, c: number, d: number) => void;
export const model_start_conversation_from_config: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const model_get_token_count: (a: number) => number;
export const __wbg_profilestats_free: (a: number, b: number) => void;
export const get_memory_info: () => [number, number];
export const get_wasm_memory_info: () => [number, number];
export const log_memory: () => void;
export const log_wasm_memory: () => void;
export const profile_enable: (a: number) => void;
export const profile_get_stats: () => number;
export const profile_print_stats: () => void;
export const profilestats_json: (a: number) => [number, number];
export const profile_clear: () => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wbg_message_free: (a: number, b: number) => void;
export const message_content: (a: number) => [number, number];
export const message_new: (a: number, b: number, c: number, d: number) => number;
export const message_role: (a: number) => [number, number];
export const memory: WebAssembly.Memory;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
