[package]
name = "bert-single-file-binary-builder"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "README.md"

[build-dependencies]
anyhow = { workspace = true }
ureq = "2.10"
