[package]
name = "candle-wasm-tests"
version.workspace = true
edition.workspace = true
description = "WASM tests for candle"
keywords.workspace = true
categories.workspace = true

[dependencies]
candle = { workspace = true }
rand = { workspace = true }
getrandom = { version = "0.3", features = ["wasm_js"], default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
