name: PyO3-Wheels

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - candle-pyo3/**
  pull_request:
    paths:
      - candle-pyo3/**
  workflow_dispatch:


env:
  PROTOC_VERSION: '25.0'
  FEATURES_FLAG: '--features onnx'

permissions: {}

jobs:
  linux:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, x86, aarch64, s390x, ppc64le]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.13'
      - name: Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad  # v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter
          sccache: 'true'
          manylinux: auto
          working-directory: ./candle-pyo3
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: wheels-linux-${{ matrix.target }}
          path: ./candle-pyo3/dist

  windows:
    permissions:
      contents: read
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64, x86]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.13'
          architecture: ${{ matrix.target }}
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b  # v3
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad  # v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter ${{ env.FEATURES_FLAG }}
          sccache: 'true'
          working-directory: ./candle-pyo3
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: wheels-windows-${{ matrix.target }}
          path: ./candle-pyo3/dist

  macos:
    permissions:
      contents: read
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
        with:
          python-version: '3.13'
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b  # v3
        with:
            version: ${{ env.PROTOC_VERSION }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build wheels
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad  # v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --find-interpreter ${{ env.FEATURES_FLAG }}
          sccache: 'true'
          working-directory: ./candle-pyo3
      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: wheels-macos-${{ matrix.target }}
          path: ./candle-pyo3/dist

  sdist:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Install Protoc
        uses: arduino/setup-protoc@a8b67ba40b37d35169e222f3bb352603327985b6  # v2
        with:
          version: ${{ env.PROTOC_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build sdist
        uses: PyO3/maturin-action@04ac600d27cdf7a9a280dadf7147097c42b757ad  # v1
        with:
          command: sdist
          args: --out dist
          working-directory: ./candle-pyo3
      - name: Upload sdist
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f  # v6
        with:
          name: wheels-sdist
          path: ./candle-pyo3/dist

