on:
  push:
    branches:
      - main
    paths:
      - flake.nix
      - flake.lock
      - .github/workflows/nix.yml
  pull_request:
    paths:
      - flake.nix
      - flake.lock
      - .github/workflows/nix.yml

name: Nix

jobs:
  flake-check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Check flake outputs
        run: nix flake check --all-systems --no-build --no-update-lock-file
